version: "3.9"

services:
  nginx:
    container_name: playlist-service-nginx
    image: playlist-service-nginx
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - services-network
  php:
    container_name: playlist-service-php
    image: playlist-service-php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - XDEBUG_MODE=${XDEBUG_MODE}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}
      - API_TOKEN=${API_TOKEN}
      - BASE_URL=${BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_PUBLIC_CERT=${JWT_PUBLIC_CERT}
      - TEST_KEY=${TEST_KEY}
    restart: unless-stopped
    networks:
      - services-network
  postgres:
    container_name: playlist-service-postgres
    restart: unless-stopped
    image: postgres:15.1
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    expose:
        - 5432
    networks:
      - services-network
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data
  redis:
    container_name: playlist-service-redis
    restart: unless-stopped
    image: redis:6.2-alpine
    expose:
      - 6379
    networks:
      - services-network
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./db/redis:/data

networks:
  services-network:
    name: services-network
    driver: bridge
